"""~200 atomic Zambia job-market skills for canonical_skills seeding (no scraper)."""

# Normalized lowercase tokens; display names come from seed title-case rules.
CURATED_ZAMBIA_SKILLS_RAW: tuple[str, ...] = (
    # Office & productivity
    "microsoft excel",
    "microsoft word",
    "microsoft powerpoint",
    "microsoft outlook",
    "microsoft access",
    "microsoft office",
    "google sheets",
    "google docs",
    "gmail",
    "typing",
    "data entry",
    # Accounting & finance
    "accounting",
    "bookkeeping",
    "financial reporting",
    "ifrs",
    "zica",
    "accca",
    "cima",
    "auditing",
    "taxation",
    "paye",
    "vat",
    "quickbooks",
    "sage evolution",
    "pastel",
    "sap",
    "erp",
    "budgeting",
    "forecasting",
    "cost control",
    "financial analysis",
    "credit analysis",
    "loan processing",
    "treasury",
    "reconciliation",
    "cash flow",
    "invoicing",
    # Banking & compliance
    "banking",
    "kyc",
    "aml",
    "compliance",
    "risk management",
    "internal controls",
    "napsa",
    # HR & admin
    "human resources",
    "recruitment",
    "payroll",
    "onboarding",
    "performance management",
    "employee relations",
    "hr policies",
    "office administration",
    "records management",
    "filing",
    # Sales & marketing
    "sales",
    "customer service",
    "customer relations",
    "retail sales",
    "merchandising",
    "marketing",
    "digital marketing",
    "social media",
    "content writing",
    "copywriting",
    "brand management",
    "market research",
    "negotiation",
    "business development",
    "key account management",
    # Soft skills (atomic)
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "time management",
    "critical thinking",
    "decision making",
    "conflict resolution",
    "presentation skills",
    "report writing",
    "research",
    "attention to detail",
    # Project & operations
    "project management",
    "project planning",
    "procurement",
    "inventory management",
    "supply chain",
    "logistics",
    "warehouse management",
    "fleet management",
    "operations management",
    "quality assurance",
    "lean manufacturing",
    "six sigma",
    "iso",
    "standard operating procedures",
    # Data & IT
    "python",
    "sql",
    "javascript",
    "java",
    "react",
    "node.js",
    "html",
    "css",
    "git",
    "docker",
    "kubernetes",
    "amazon web services",
    "microsoft azure",
    "google cloud platform",
    "cybersecurity",
    "networking",
    "it support",
    "troubleshooting",
    "system administration",
    "database administration",
    "power bi",
    "tableau",
    "data analysis",
    "data visualization",
    "machine learning",
    "artificial intelligence",
    "etl",
    "api development",
    # Engineering & technical trades
    "autocad",
    "civil engineering",
    "structural design",
    "quantity surveying",
    "electrical engineering",
    "mechanical engineering",
    "maintenance",
    "plc",
    "hvac",
    "welding",
    "fabrication",
    "cnc machining",
    "instrumentation",
    "scada",
    "bim",
    "surveying",
    "gis",
    # HSE & environment
    "hse",
    "health and safety",
    "occupational health",
    "environmental management",
    "waste management",
    # Healthcare
    "nursing",
    "patient care",
    "pharmacy",
    "laboratory",
    "clinical data",
    "medical records",
    # Education
    "teaching",
    "lesson planning",
    "curriculum development",
    "classroom management",
    # Agriculture & mining
    "agriculture",
    "extension services",
    "crop production",
    "livestock management",
    "mining",
    "geology",
    "drilling",
    "blasting",
    # NGO & governance
    "ngo management",
    "grant writing",
    "monitoring and evaluation",
    "stakeholder management",
    "governance",
    "fundraising",
    # Hospitality & services
    "hospitality",
    "front office",
    "food production",
    "housekeeping",
    "event management",
    "public relations",
    # Transport & security
    "driving",
    "defensive driving",
    "forklift operation",
    "security management",
    "cctv monitoring",
    # Legal & real estate
    "contract management",
    "legal research",
    "property management",
    "estate agency",
    # Telecom & media
    "telecommunications",
    "fiber installation",
    "graphic design",
    "video editing",
    "photography",
    # Construction management
    "site supervision",
    "cost estimation",
    "contract administration",
    "health and safety plans",
    # Miscellaneous professional
    "translation",
    "interpretation",
    "archiving",
    "inventory control",
    "cash handling",
    "stock control",
    "point of sale",
    "crm",
    "sharepoint",
    "microsoft teams",
    "zoom administration",
)
